### ISSUE TITLE
Planned Additions/Fixes for 0.1.0

### ISSUE THREAD

**Issue by petabyt** [heb12/heb12-mobile#3]
- [x] Add a few more translations
- [x] Add themes
- [x] Finish search function
- [x] Reposition the Random button
- [x] Add verse of the day
- [x] Add a mobile view to the website (not really related to the app)
- [x] Speed improvement
- [x] Bookmarks
- [x] Redesign the sidebar
- [ ] Add swiping to the sidebar
- [x] Make link/button to go to verse in VOTD
- [x] Verse popup shows when trying to close the sidebar
- [x] Verse popup shows when switching chapters/books

**Comment by MasterOfTheTiger** [comment]
Can you add instructions in the README for development instructions? Like setting it up in Android Studio.

**Comment by petabyt** [comment]
I was thinking about doing something like that in the wiki page. https://github.com/heb12/heb12-mobile/wiki

**Comment by MasterOfTheTiger** [comment]
@pufflegamerz Maybe, or maybe a development.md or something. We need something in a better place than the wiki, because it needs to be downloaded when someone clones the repo.

**Comment by MasterOfTheTiger** [comment]
Either way, it should be added.

**Comment by petabyt** [comment]
I think the app is ready to be released. I've fixed most of the major problems. Tell me if you find any bugs.

**Comment by MasterOfTheTiger** [comment]
Sorry. But I think we need more translations for more people to accept it. Don't you think? Maybe we should release the app as version 0.1.0 (following semantic versioning) now.

**Comment by petabyt** [comment]
I was hesitant about adding more translations, because it might make the app slower, and it already takes a while to load. What translations should I add? I don't see myself using more than 2.

**Comment by MasterOfTheTiger** [comment]
Okay. We need a better solution then. Can we load them into RAM only after they are selected?

**Comment by petabyt** [comment]
I just figured out a way to load the bible files only when a new translation is selected. I tried to do it before, and it didn't work. I guess I did something different and now it functional.

**Comment by MasterOfTheTiger** [comment]
Another few things which need to be done: 

- [x] Fix KJV 2000 verse selection (I can't get it to select the right verse for some reason)
- [x] Support verse selection in NET 
- [x] Fix "next" and "previous" for KJV 2000 when next or previous is different book. 

You should be able to reproduce all those issues. I found them in the 13th's version of the app. So you may have fixed some. 

Here are some more things which should probably be done: 

- [x] Font size configuration (in addition to fixing the font size with the NET translation)
- [x] Change version number in info screen from 1.0 to 0.1.0 

- [x] Improve code and documentation for other developers and contributors.

**Comment by MasterOfTheTiger** [comment]
Not sure you can do much about this, but it would be pretty useful to be able to use the up and down arrow keys on an Android hardware keyboard to move up and down on the Bible passage.

**Comment by MasterOfTheTiger** [comment]
Another thing we should do before the new version is released is the ability to easily compare versions in the popup. You can decide the best way to impliment it.

**Comment by petabyt** [comment]
Ok. I'll look into the issues. About the android keyboard part, are you talking about an external keyboard?

**Comment by MasterOfTheTiger** [comment]
Yes I am. It isn't a big deal, but I was trying to scroll down with the arrow keys and it didn't works. Kinda odd for a web based app when you think about it. 

Another question is, how hard would this app be to translate? Do you use external Android strings?

**Comment by MasterOfTheTiger** [comment]
Another thing is, could you possibly be more descriptive in your commit messages? That's kinda important for both other contributors and for looking back at code later.

**Comment by MasterOfTheTiger** [comment]
Another bug: 
- When clicking previous at chapter 1 of James, it goes to Hebrews 5 instead of 13 on the ASV translation.

**Comment by MasterOfTheTiger** [comment]
Ouch. The NET seems to be entirely broken. It says "undefined" where the Scripture should be.

**Comment by petabyt** [comment]
Press next, it should work.

**Comment by petabyt** [comment]
I attached a keyboard to my phone and the scrolling with arrow keys worked.

**Comment by MasterOfTheTiger** [comment]
Oh, I understand now. It kinda works like TAB  by selecting all of the verse numbers. The NET still doesn't work, and the previous button should be fixed. It is entirely inconsistent.

**Comment by petabyt** [comment]
I fixed some of the issues. The NET should work now.

**Comment by petabyt** [comment]
I kinda want to make a dedicated website for Heb12 Mobile, because the one we have right now just looks a little plain.

**Comment by MasterOfTheTiger** [comment]
Okay. You can do that. Put it in a gh-pages branch

**Comment by petabyt** [comment]
I put it in the `docs` directory. [https://heb12.ml/heb12-mobile/](https://heb12.ml/heb12-mobile/) Do you think it looks good? I will definitely change it a lot later on.

**Comment by MasterOfTheTiger** [comment]
Awesome! I like it. 

By the way, how can I help with Heb12 Mobile? What do you need me to do?

**Comment by MasterOfTheTiger** [comment]
And how does the verse of the day code work?

**Comment by petabyt** [comment]
Thanks! The side menu definitely needs some touching up, and the online NET translation css needs some work. The verse of the day comes from the Bible Labs API. http://labs.bible.org/api/?passage=votd

**Comment by MasterOfTheTiger** [comment]
@pufflegamerz If I have a chance I will work on it. We need to do as much work as we can in the next week. Hopefully we can publish it on Google Play within a week (at least some kind of beta). Then later F-Droid as well.

**Comment by petabyt** [comment]
I'm pretty sure there is a $25 fee to get a developer account on Google Play. The Amazon App store is free though.

**Comment by MasterOfTheTiger** [comment]
Yeah. I know. I might see about paying it if I can. 

I'll see about putting it in the Amazon app store. F-Driod is also free but can be cumbersome.

**Comment by petabyt** [comment]
You don't have to.  I have an Amazon Developer account where I published a couple of apps a couple of years ago.

**Comment by MasterOfTheTiger** [comment]
@pufflegamerz. Okay. But to be honest, I would like to have access to it somehow. Because I am the owner of Heb12. Of course you are the lead (and only) developer of Heb12 Mobile, so I am fine with you publishing it. Once we agree on the release of 0.1.0 you can publish it.

**Comment by petabyt** [comment]
Could I make a folder in the heb12.github.up repository named Mobile so I can put the website in it? The code and website probably shouldn't be in the same repository.

**Comment by MasterOfTheTiger** [comment]
Yes. That is totally fine.

**Comment by MasterOfTheTiger** [comment]
@pufflegamerz Verse selection in NET is very broken.

**Comment by petabyt** [comment]
It works for me. What book and chapter is it?

**Comment by petabyt** [comment]
Oh. I see it. The highlighting won't work.I'll investigate.

**Comment by petabyt** [comment]
The API sends the text in some wierd format:
http://labs.bible.org/api/?passage=John%203&type=json&callback=myfunction

**Comment by petabyt** [comment]
http://labs.bible.org/api/?passage=John%203&type=json&callback=myfunction&&formatting=full

**Comment by MasterOfTheTiger** [comment]
@pufflegamerz  In addition, normal verse selection doent seem to be working consistently.

**Comment by petabyt** [comment]
It should work in the latest apk.

**Comment by petabyt** [comment]
For some reason, I uploaded an older apk file. It should work now.

**Comment by MasterOfTheTiger** [comment]
The font size still does not work. It reads "NaN". I am able to change the Heb12 config file to a valid number to change this though. 

Plus. Shouldn't the config file be in the Android assigned location for heb12? (Android/data/io.github.heb12.heb12mobile or something like that).that should fix the storage problem.

**Comment by petabyt** [comment]
Hmmm. It works good on my phone. What version of Android are you using?

**Comment by MasterOfTheTiger** [comment]
5.0. But shouldn't that be irrelevent? Try deleting the app and the configuration file and try again.

**Comment by MasterOfTheTiger** [comment]
By the way Android 4.x doesn't work. It installs, but the app gets stuck at the loading part.

**Comment by petabyt** [comment]
I'm pretty sure every version has a different webview version.

**Comment by petabyt** [comment]
There might be a way to update it though.

**Comment by MasterOfTheTiger** [comment]
You need to make sure that it opens the last Bible translation used (if you haven't done that already).

**Comment by petabyt** [comment]
I've tried making that work for hours, but I was never able to fix it.

**Comment by MasterOfTheTiger** [comment]
Odd. Shouldn't it work the same as storing previously opened books and chapters? Either way, that is a pretty big deal as it is expected to work that way...

**Comment by petabyt** [comment]
It gets stored in the config file, then when the app opens It goes to the default. I'll try my best to fix it.

**Comment by MasterOfTheTiger** [comment]
Okay. Thanks! I am going to download Android Studio myself right now and see if I can help with something later.

**Comment by MasterOfTheTiger** [comment]
Okay. I am closing this now since 0.1.0 is released. Open new issues for individual features from now on I guess.
